project_name: pwgen
before:
  hooks:
    - go mod download

builds:
  -
    id: "client"
    dir: "."
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.date={{.CommitDate}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm64
release:
  prerelease: true

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64
    wrap_in_directory: true
    format_overrides:
    - goos: darwin
      format: tar.xz
    - goos: linux
      format: tar.xz
    files:
      - LICENSE
      - README.md

brews:
  -
    tap:
      owner: grimdork
      name: homebrew-tools
    commit_author:
      name: Urethramancer
      email: github@grimdork.net
    homepage: "https://github.com/grimdork/pwgen"
    description: "A password generator with a few different variations."
    license: "MIT"
    skip_upload: auto

nfpms:
  -
    replacements:
      darwin: macOS
      linux: Linux
    vendor: grimdork.net
    homepage:
    maintainer: Ronny Bangsund <github@grimdork.net>
    description:
    formats:
      - deb
      - rpm
    dependencies:
    bindir: /usr/bin
    section: contrib
    priority: extra
    contents:
      - src: LICENSE
        dst: /usr/share/doc/name/LICENSE

      - src: README.md
        dst: /usr/share/doc/name/README.md

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

signs:
  - artifacts: checksum
    args: ["--batch", "-u", "{{ .Env.GPG_FINGERPRINT }}", "--output", "${signature}", "--detach-sign", "${artifact}"]
